export const FOCUS_SCORE_CONFIG = {
  BASE_SCORE: 100,
  MIN_DURATION_SECONDS: 60,
  PENALTIES: {
    DISTRACTION_PER_COUNT: 2,
    DISTRACTION_MAX: 40,
    PAUSE_PER_COUNT: 5,
    PAUSE_MAX: 20,
    TAB_SWITCH_DIVISOR: 5,
    TAB_SWITCH_PENALTY: 2,
    TAB_SWITCH_MAX: 10,
  },
  ACTIVE_RATIO_THRESHOLD: 0.7,
  ACTIVE_RATIO_MULTIPLIER: 50,
  GRADES: {
    A: 90,
    B: 80,
    C: 70,
    D: 60,
  },
} as const;

export const FOCUS_INSIGHT_THRESHOLDS = {
  EXCELLENT_SCORE: 90,
  GOOD_SCORE: 70,
  HIGH_DISTRACTION_COUNT: 10,
  HIGH_TAB_SWITCH_COUNT: 15,
  HIGH_PAUSE_COUNT: 5,
  SHORT_SESSION_SECONDS: 300,
  LONG_SESSION_SECONDS: 3600,
} as const;
